name: Analyze, test and build
on:
	push:
		branches:
		- master
	pull_request:

jobs:
	lint: 
		name: Analyze the code
		runs-on: ubuntu-latest
		steps:
			- name: Clone flutter repository from stable channel
				uses: subosito/flutter-actions@v1
				with:
					flutter-version: '2.8.0'
					channel: 'stable'
			- name: Checkout code
				uses: actions/checkout@v2
			- name: update dependencies
				run: flutter pub get
			- name: Analyze code
				run: flutter analyze

	test:

	build: